spring:
  datasource:
    url: jdbc:mysql://120.25.216.49/store?allowMultiQueries=true
    password: 111111
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
user:
  address:
    max_count: 5
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
server:
  port: 8800
#  redis:
#    host: 120.25.216.49
#  data:
#    mongodb:
#      uri: mongodb://120.25.216.49/testdb
#      username: root
#      password: 123456
#logging:
#  file:
#    name: server.log
